
---

## **📄 _config.yml**
```yaml
title: "Lab - Deploy a Pre-Built Kali Linux Virtual Machine"
description: "Step-by-step guide for deploying a pre-built Kali Linux VM on Windows using VirtualBox."
remote_theme: "mmistakes/minimal-mistakes"

# Author info
author:
  name: "Your Name"
  bio: "Network & Security Engineer | Cybersecurity Enthusiast"

# Theme skin
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md

# URL settings
url: "https://YOUR-USERNAME.github.io"
baseurl: "/Lab-Kali-Linux-VM"
